VERSION 0.7

FROM haxe:4.3.1-bullseye
WORKDIR /hxminetest
RUN haxelib dev hxminetest .

deps:

    # Install Deno
    RUN apt-get update && \
        apt-get install -y unzip && \
        curl -fsSL https://deno.land/x/install/install.sh | sh
    ENV DENO_INSTALL /root/.deno
    ENV PATH $DENO_INSTALL/bin:$PATH

    # Cache Deno deps
    COPY scripts/deps.ts scripts/deps.ts
    RUN deno cache scripts/deps.ts

    # Install Haxe deps
    COPY haxelib.json .
    RUN haxelib install haxelib.json --always

lint:

    RUN haxelib install formatter

    COPY hxformat.json .
    COPY examples examples
    COPY src src
    RUN haxelib run formatter --check -s examples -s src

build-examples:

    FROM +deps

    COPY extraParams.hxml .
    COPY examples examples
    COPY scripts scripts
    COPY src src
    RUN deno run --allow-run=haxe --allow-read=examples scripts/build-examples.ts

build-docs-api:

    FROM +deps

    RUN mkdir docs && mkdir docs/.vitepress && mkdir docs/reference
    COPY scripts scripts
    COPY src src
    RUN deno run --allow-run --allow-read=docs --allow-write=docs scripts/generate-class-reference.ts

    SAVE ARTIFACT docs/.vitepress/reference-sidebar.autogenerated.ts
    SAVE ARTIFACT docs/reference/minetest

build-docs:

    FROM node:20-alpine3.18
    WORKDIR /docs

    # Install pnpm
    ENV SHELL /bin/sh
    ENV PNPM_HOME $HOME/.local/share/pnpm
    ENV PATH $PNPM_HOME:$PATH
    RUN wget -qO- https://get.pnpm.io/install.sh | sh - || true

    # Cache JS deps
    ENV CI 1
    COPY docs/package.json docs/pnpm-lock.yaml .
    RUN pnpm install

    COPY docs .
    COPY +build-docs-api/reference-sidebar.autogenerated.ts .vitepress/reference-sidebar.autogenerated.ts
    COPY +build-docs-api/minetest reference/minetest
    RUN pnpm vitepress build .
    SAVE ARTIFACT .vitepress/reference-sidebar.autogenerated.ts AS LOCAL docs/.vitepress/reference-sidebar.autogenerated.ts
    SAVE ARTIFACT .vitepress/dist AS LOCAL docs/.vitepress/dist
