VERSION 0.8

FROM haxe:4.3.4-alpine3.20
WORKDIR /hxminetest

RUN haxelib dev hxminetest .

ENV DENO_FUTURE 1
RUN apk add --no-cache git wget deno

deps:

    # Cache Deno deps
    COPY scripts/deps.ts scripts/deps.ts
    RUN deno cache scripts/deps.ts

    # Install Haxe deps
    RUN haxelib install formatter
    COPY haxelib.json .
    RUN haxelib install haxelib.json --always

lint:

    FROM +deps

    COPY hxformat.json .
    COPY examples examples
    COPY src src
    RUN haxelib run formatter --check -s examples -s src

build-examples:

    FROM +deps

    COPY extraParams.hxml .
    COPY examples examples
    COPY scripts scripts
    COPY src src
    RUN deno run --allow-run=haxe --allow-read=examples scripts/build-examples.ts

build-docs-generate-reference:

    FROM +deps

    RUN mkdir docs && mkdir docs/.vitepress && mkdir docs/reference
    COPY scripts scripts
    COPY src src
    RUN deno run --allow-run --allow-read=docs --allow-write=docs scripts/generate-class-reference.ts

    # These artifacts do not have to be local to build the final HTML version,
    # but we can use them for hot-reloading a dev server on a host machine (vitepress dev docs)
    SAVE ARTIFACT docs/.vitepress/reference-sidebar.autogenerated.ts AS LOCAL docs/.vitepress/reference-sidebar.autogenerated.ts
    SAVE ARTIFACT docs/reference/minetest AS LOCAL docs/reference/minetest

build-docs-static-html:

    RUN apk add --no-cache nodejs
    WORKDIR /docs

    # Install pnpm
    ENV SHELL /bin/sh
    ENV PNPM_HOME $HOME/.local/share/pnpm
    ENV PATH $PNPM_HOME:$PATH
    RUN wget -qO- https://get.pnpm.io/install.sh | sh - || true

    # Cache JS deps
    ENV CI 1
    COPY docs/package.json docs/pnpm-lock.yaml .
    RUN pnpm install

    # Build Vitepress site
    COPY docs .
    COPY +build-docs-generate-reference/reference-sidebar.autogenerated.ts .vitepress/reference-sidebar.autogenerated.ts
    COPY +build-docs-generate-reference/minetest reference/minetest
    RUN pnpm vitepress build .
    SAVE ARTIFACT .vitepress/dist AS LOCAL docs/.vitepress/dist

build-docs:
    BUILD +build-docs-generate-reference
    BUILD +build-docs-static-html
