import { defineConfig } from 'vitepress'
import referenceSidebar from './reference-sidebar.autogenerated'

// https://vitepress.dev/reference/site-config

export default defineConfig({

  title: "HxMinetest",
  description: "Documentation",

  ignoreDeadLinks: true,

  themeConfig: {

    // https://vitepress.dev/reference/default-theme-config
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Reference', link: '/reference/minetest/Minetest' }
    ],

    sidebar: {

      "/guide/": [
        {
          text: 'Introduction',
          items: [
            { text: 'About HxMinetest', link: '/guide/about' },
            { text: 'Getting started', link: '/guide/getting-started' },
          ]
        },
        {
          text: 'Writing mods',
          items: [
            { text: 'Your first mod', link: '/guide/tutorial/your-first-mod' },
          ]
        }
      ],

      "/reference/": referenceSidebar,

    },

    socialLinks: [
      {
        icon: 'github',
        link: 'https://github.com/frixuu/hxminetest/',
      }
    ]
  }
})
