name: "Examples"

on:
  push:
    paths:
      - "**.hx"
      - "**.ts"
      - ".github/workflows/**.yml"
  pull_request:
    paths:
      - "**.hx"
      - "**.ts"
      - ".github/workflows/**.yml"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        haxe-version: ["4.3.0", "latest"]
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - name: "Install Haxe"
        uses: "krdlab/setup-haxe@v1"
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: "Install Deno"
        uses: "denoland/setup-deno@v1"
        with:
          deno-version: "^1.35"
      - name: "Build example mods"
        run: |
          haxelib install haxelib.json --always
          haxelib dev hxminetest .
          deno run --allow-run=haxe --allow-read=examples scripts/build-examples.ts
