name: Build examples

on:
  push:
    paths:
      - "**.hx"
      - "**.ps1"
      - ".github/workflows/**.yml"
  pull_request:
    paths:
      - "**.hx"
      - "**.ps1"
      - ".github/workflows/**.yml"

jobs:
  build:
    name: "Build included examples"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        haxe-version: ["4.3.0", "latest"]
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - name: "Install Haxe"
        uses: "krdlab/setup-haxe@v1"
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: "Update Powershell version"
        run: |
          wget https://github.com/PowerShell/PowerShell/releases/download/v7.3.3/powershell_7.3.3-1.deb_amd64.deb -O pwsh.deb
          sudo dpkg -i pwsh.deb
          sudo apt-get install -f
      - name: "Compile example mods"
        run: |
          haxelib dev hxminetest .
          haxelib install haxelib.json --always
          pwsh scripts/build_examples.ps1
