name: Build examples

on:
  push:
    paths:
      - "**.hx"
      - "**.ps1"
      - ".github/workflows/**.yml"
  pull_request:
    paths:
      - "**.hx"
      - "**.ps1"
      - ".github/workflows/**.yml"

jobs:
  build:
    name: "Build included examples"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        haxe-version: ["4.3.0", "latest"]
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - name: "Install Haxe"
        uses: "krdlab/setup-haxe@v1"
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: "Compile example mods"
        run: |
          haxelib dev hxminetest .
          pwsh scripts/build_examples.ps1
